import matplotlib as mpl
import vdd.load
from functools import cached_property as cached_property

class CompareOB16WithCESM:
    @cached_property
    def dec_ob16(self) -> vdd.load.DeconvolveOB16: ...
    @cached_property
    def dec_cesm(self) -> vdd.load.DeconvolveCESM: ...
    def plot_rf(self) -> mpl.figure.Figure: ...
    def plot_temp(self) -> mpl.figure.Figure: ...
