import numpy as np
from scipy.optimize import OptimizeResult as OptimizeResult

def deconv_mean_2(signal, forcing) -> OptimizeResult: ...
def alternative_deconv(signal: np.ndarray, forcing: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...
