import numpy as np
from numpy.typing import NDArray as NDArray
from scipy.optimize import OptimizeResult as OptimizeResult

def deconv_mean_2(signal: NDArray[np.float64], forcing: NDArray[np.float64]) -> OptimizeResult: ...
def alternative_deconv(signal: np.ndarray, forcing: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...
