import numpy as np

def shapes_different_timescales() -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
def shapes_different_rise() -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
def correlation_test() -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...
