from _typeshed import Incomplete as Incomplete

class Pipe:
    value: Incomplete
    func: Incomplete
    def __init__(self, value, func: Incomplete | None = None) -> None: ...
    def __getitem__(self, func) -> None: ...
    def __call__(self, *args, **kwargs) -> None: ...
    def __rrshift__(self, *args, **kwargs) -> None: ...

class MetaFunc:
    func: Incomplete
    def __init__(self, func) -> None: ...
    def __call__(self, *args) -> None: ...
    def __or__(self, other) -> None: ...
