on:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: googleapis/release-please-action@v4
      id: release
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        config-file: .github/release-please/release-please-config.json
        manifest-file: .github/release-please/release-please-manifest.json

  validate:
    needs: release-please
    name: validate
    runs-on: ubuntu-latest
    steps:
    - name: Check out a copy of the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        ref: ${{ steps.release.outputs.pr }}
        persist-credentials: false

    - name: Check whether the citation metadata from CITATION.cff is valid
      uses: citation-file-format/cffconvert-github-action@2.0.0
      with:
        args: --validate
